// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { CartProvider } from "../utils/cartContext"; // ✅ import here
// import Navbar from "./components/navBar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       
//         <CartProvider> <Navbar/>
//           {children}
//           </CartProvider> {/* ✅ Only once */}
//       </body>
//     </html>
//   );
// }


import './globals.css';
import Navbar from '../components/Navbar';

export const metadata = {
  title: 'MCQ & Compiler'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 min-h-screen">
        <Navbar />
        <main className=" mx-auto p-4">{children}</main>
      </body>
    </html>
  );
}
